version: '3'

services:
  tetengo_data:
    image: busybox
    volumes:
      - data-volume:/mnt/data

  tetengo_base:
    build:
      context: tetengo_base
    image: tetengo/base

  tetengo_gcc:
    build:
      context: tetengo_gcc
    image: tetengo/gcc
    depends_on:
      - tetengo_base

  tetengo_clang:
    build:
      context: tetengo_clang
    image: tetengo/clang
    depends_on:
      - tetengo_base

  devenv_tetengo_gcc:
    image: tetengo/gcc
    depends_on:
      - tetengo_data
      - tetengo_gcc
    volumes:
      - data-volume:/mnt/data
      - C:\data:/mnt/host_data
    user: docker
    working_dir: /home/docker
    stdin_open: true
    tty: true

  devenv_tetengo_clang:
    image: tetengo/clang
    depends_on:
      - tetengo_data
      - tetengo_clang
    volumes:
      - data-volume:/mnt/data
      - C:\data:/mnt/host_data
    user: docker
    working_dir: /home/docker
    stdin_open: true
    tty: true

volumes:
  data-volume:
